
common:

  output_directory: data/ga/NCI/processed

steps:

  - type: filter
    parameters:
      inputs: [NCI_00.bz2]
      outputs: [NCI_00-filtered_0.bz2]
      filters:
        - LengthFilter:
            unit: word
            min_length: 1
            max_length: 100

        - LongWordFilter:
            threshold: 40

        - HtmlTagFilter: {}

        - PunctuationFilter:
            threshold: 0.4
          module: customfilters

        - DigitsFilter:
            threshold: 0.4
          module: customfilters

