
# run 'python scripts/text_processor.py --datasets gdrive --bucket-size 10000000'
# to generate 'gdrive_00.bz2'

common:

  output_directory: data/ga/gdrive/processed

steps:

  - type: filter
    parameters:
      inputs: [gdrive_00.bz2]
      outputs: [gdrive_00-filtered_1.bz2]
      filters:
        - LengthFilter:
            unit: word
            min_length: 1
            max_length: 100

        - LongWordFilter:
            threshold: 40

        - HtmlTagFilter: {}

        - CharacterScoreFilter:
            scripts: [Latin]
            thresholds: [1.0]

        - LanguageIDFilter:
            name: langid
            id_method: langid
            languages: [ga]
            thresholds: [1.0]

        - LanguageIDFilter:
            name: cld2
            id_method: cld2
            languages: [ga]
            thresholds: [1.0]

        - PunctuationFilter:
            threshold: 0.4
          module: customfilters

        - DigitsFilter:
            threshold: 0.4
          module: customfilters

