common:
  output_directory: data/ga/paracrawl   

steps:
  - type: opus_read
    parameters:
      corpus_name: ParaCrawl
      source_language: ga
      target_language: en
      release: latest
      preprocessing: raw
      src_output: paracrawl.ga.gz
      tgt_output: paracrawl.en.gz
